### PR TITLE
1/logout route

### LINKED ISSUE #1: Going to /logout doesn't logout the user
(hi @VictorPeralta this is the best starter I've found after hours of headbanging. Thank you so much!)

Issue: going directly to `/logout` will not end the session

Repro steps:
- With the code as is (no modification)
- login
- go to `/logout`

Actual behavior:
- the index show user id info

Expected behavior
- back to unauthed state where it shows `You're not logged in `

Using the logout button works fine.

### PR DESCRIPTION
**Pull request by VictorPeralta**
Users that visit `/logout` will now be logged out both client and serverside. Closes #1

### CODE REVIEW

**Comment by bernatfortet** [comment]
Thanks 👍

File: app/useUser.tsx [hunk 1]
```diff
@@ -61,8 +52,19 @@ export const UserContextProvider = ({ children }: { children: ReactChild }) => {
     };
   }, []);
 
+  useEffect(() => {
```
Comment (bernatfortet) [inline app/useUser.tsx:55]: Is it good to separate these in two useEffects?

File: app/sessions.server.ts [hunk 2]
```diff
@@ -64,7 +64,7 @@ export async function getLoggedInUser(request: Request): Promise<User | null> {
 /** Destroy the session cookie  */
 export async function clearCookie(request: Request) {
   let session = await storage.getSession(request.headers.get("Cookie"));
-  return redirect("/", {
+  return json("/", {
```
Comment (bernatfortet) [inline app/sessions.server.ts:67]: Just curious, why use json instead of redirect?

File: app/useUser.tsx (hunk 1 above)
Comment (VictorPeralta) [reply app/useUser.tsx:55]: Doesn't really matter one way or the other, maybe should put them back into one, I was testing something and didn't revert this code

File: app/sessions.server.ts (hunk 2 above)
Comment (VictorPeralta) [reply app/sessions.server.ts:67]: Loaders are executed before the page is rendered in Remix, and this code is used by the loaders in `/logout`. If I used a redirect, the loader would cause a redirect before the clientside log out occurred

Comment (bernatfortet) [reply app/sessions.server.ts:67]: Gotcha. thanks
